---
version: "3.6"

volumes:
  registry-data:

networks:
  net:
    driver: "overlay"

services:
  cleanup:
    build:
      context: "cleanup"
    image: "127.0.0.1:5000/registry-cleanup"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - "net"
    deploy:
      placement:
        constraints:
          - "node.labels.onup.host==env"
  registry:
    image: "registry"
    environment:
      - REGISTRY_STORAGE_DELETE_ENABLED=true
    volumes:
      - "registry-data:/var/lib/registry"
    networks:
      - "net"
    ports:
      - "5000:5000"
    deploy:
      placement:
        constraints:
          - "node.labels.onup.host==env"

# vim:sw=2:
