---
version: "3.6"

volumes:
  registry-data:

networks:
  net:
    driver: "overlay"

services:
  cleanup:
    build:
      context: "cleanup"
    image: "PC-Vincent:5000/registry-cleanup"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - "net"
    deploy:
      restart_policy:
        condition: any
        delay: 24h
  registry:
    image: "registry"
    environment:
      - REGISTRY_STORAGE_DELETE_ENABLED=true
    volumes:
      - "registry-data:/var/lib/registry"
    networks:
      - "net"
    ports:
      - "5000:5000"

# vim:sw=2:
