---
version: "3.6"

volumes:
  registry-data:

networks:
  net:
    driver: "overlay"

services:
  registry:
    build:
      context: "./registry"
    image: "127.0.0.1:5000/registry"
    volumes:
      - "registry-data:/var/lib/registry"
    networks:
      - "net"
    ports:
      # registry
      - "5000:5000"
