version: "3.7"

networks:
  net:
    driver: "overlay"

volumes:
  data:

services:
  registry:
    image: "registry:latest"
    volumes:
      - "data:/var/lib/registry"
    networks:
      - "net"
    ports:
      - "5000:5000"

# vim:sw=2:
