---
version: "3.6"

volumes:
  registry-data:

networks:
  net:
    driver: "overlay"

services:
  registry:
    image: "registry"
    volumes:
      - "registry-data:/var/lib/registry"
    networks:
      - "net"
    ports:
      - "5000:5000"

# vim:sw=2:
